sudo: required
services:
  - docker

before_install:
  - docker build -t 307949230/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 307949230/client-test npm test -- --coverage

after_success:
  # # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # # Take those images and push them to docker hub
  - docker build -t 307949230/mern-client ./client
  - docker build -t 307949230/mern-nginx ./nginx
  - docker build -t 307949230/mern-server ./server
  - docker push 307949230/mern-client
  - docker push 307949230/mern-nginx
  - docker push 307949230/mern-server
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: avian
  env: Avian-env
  bucket_name: elasticbeanstalk-us-east-1-119967030140
  bucket_path: avian
  on:
    branch: avian
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
