version: "3"
services:
  mongo:
    image: "mongo:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
    links:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/cheburashka
      - SECRET_OR_KEY=cheburashka
    links:
      - mongo
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
